---
title: "child_corpus"
author: "David Rose"
date: "`r Sys.Date()`"
output: html_document
---

# Load Packages
```{r}

library("janitor")
library("tidyverse")

```

#Gelman
## 1998-Books

```{r}


folder_path1 = "../../data/Gelman/1998-Books/picturebook20/"
folder_path2 = "../../data/Gelman/1998-Books/picturebook35/"
folder_path3 = "../../data/Gelman/1998-Books/readingbook30/"

file_list1 = list.files(folder_path1, pattern = "*.cha$")
file_list2 = list.files(folder_path2, pattern = "*.cha$")
file_list3 = list.files(folder_path3, pattern = "*.cha$")

file_lists = list(file_list1, file_list2, file_list3)
folder_paths = list(folder_path1, folder_path2, folder_path3)
folder_names = c(basename(folder_path1), basename(folder_path2), basename(folder_path3))

df_list = list()

for (j in 1:length(file_lists)) {
  file_list = file_lists[[j]]
  folder_path = folder_paths[[j]]
  folder_name = folder_names[j]
  format = str_extract(folder_name, "\\D+")
  age = as.numeric(str_extract(folder_name, "\\d+"))
  
  for (i in 1:length(file_list)) {
    filename = file.path(folder_path, file_list[i])
    lines = read_lines(filename)
    file_index = str_remove(file_list[i], ".cha")
    df = tibble(lines) %>%
      mutate(file_index = file_index, format = format, age = age)
    df_list[[length(df_list) + 1]] = df
  }
}

df.gelman.books = bind_rows(df_list)

```

```{r}

df.gelman.books = df.gelman.books %>% 
  clean_names() %>% 
   mutate(mother = str_extract(lines, "(?<=MOT:)(.*)"),
          child = str_extract(lines, "(?<=CHI:)(.*)")) %>% 
  pivot_longer(cols = mother:child,
               names_to = "person_speaking",
               values_to = "text") %>% 
   mutate(participant = match(file_index, unique(file_index)),
          child_gender = if_else(file_index %in% c(26, 31, 32, 37, 39, 41, 43, 46, 3, 4, 11, 15, 17, 24, 48, 5, 7, 9, 14, 21, 22, 23, 34), "female", "male")) %>% 
  select(-lines) %>% 
  drop_na()

write.csv(df.gelman.books, "../../data/gelman_books.csv")

```



## 2016-Robodog

```{r}

folder_path <- "../../data/Gelman/2016-Robodog/"
file_list <- list.files(folder_path, pattern = "*.cha$")
df_list <- list()

for (i in 1:length(file_list)) {
  filename <- file.path(folder_path, file_list[i])
  lines <- read_lines(filename)
  file_index <- str_remove(file_list[i], ".cha")
  df <- tibble(lines) %>%
    mutate(file_index = file_index)
  df_list[[i]] <- df
}

df.gelman.robodog <- bind_rows(df_list)

```

```{r}

df.gelman.robodog = df.gelman.robodog %>% 
  clean_names() %>% 
   mutate(mother = str_extract(lines, "(?<=MOT:)(.*)"),
          child = str_extract(lines, "(?<=CHI:)(.*)")) %>% 
  pivot_longer(cols = mother:child,
               names_to = "person_speaking",
               values_to = "text") %>% 
   mutate(participant = match(file_index, unique(file_index)),
          age = if_else(file_index %in% c(12, 13, 14, 17, 18, 21, 23, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56), 60, 36)) %>% 
  select(-lines) %>% 
  drop_na()

write.csv(df.gelman.robodog, "../../data/gelman_robodog.csv")

```


#Bates

```{r}


folder_path1 = "../../data/Bates/Free20/"
folder_path2 = "../../data/Bates/Free28/"
folder_path3 = "../../data/Bates/Snack28/"
folder_path4 = "../../data/Bates/Story28/"

file_list1 = list.files(folder_path1, pattern = "*.cha$")
file_list2 = list.files(folder_path2, pattern = "*.cha$")
file_list3 = list.files(folder_path3, pattern = "*.cha$")
file_list4 = list.files(folder_path4, pattern = "*.cha$")

file_lists = list(file_list1, file_list2, file_list3, file_list4)
folder_paths = list(folder_path1, folder_path2, folder_path3, folder_path4)
folder_names = c(basename(folder_path1), basename(folder_path2), basename(folder_path3), basename(folder_path4))

df_list = list()

for (j in 1:length(file_lists)) {
  file_list = file_lists[[j]]
  folder_path = folder_paths[[j]]
  folder_name = folder_names[j]
  format = str_extract(folder_name, "\\D+")
  age = as.numeric(str_extract(folder_name, "\\d+"))
  
  for (i in 1:length(file_list)) {
    filename = file.path(folder_path, file_list[i])
    lines = read_lines(filename)
    file_index = str_remove(file_list[i], ".cha")
    df = tibble(lines) %>%
      mutate(file_index = file_index, format = format, age = age)
    df_list[[length(df_list) + 1]] = df
  }
}

df.bates = bind_rows(df_list)

```

```{r}

df.bates = df.bates %>% 
  clean_names() %>% 
   mutate(mother = str_extract(lines, "(?<=MOT:)(.*)"),
          child = str_extract(lines, "(?<=CHI:)(.*)")) %>% 
  pivot_longer(cols = mother:child,
               names_to = "person_speaking",
               values_to = "text") %>% 
   mutate(participant = match(file_index, unique(file_index)),
          child_gender = if_else(file_index %in% c("amy", "betty", "gloria", "ivy", "jane", "kathy", "linda", "mandy", "nan", "olivia", "paula", "ruth", "sue", "vicki", "wanda", "amy28", "betty28", "gloria28", "ivy28", "linda28", "mandy28", "nan28", "olivia28", "paula28", "ruth28", "sue28", "wanda28", "ruth_snack", "amyst", "bettyst", "gloriast", "ivyst", "lindast", "mandyst", "nanst", "oliviast", "paulast", "ruthst", "suest", "wandast"), "female", "male")) %>% 
  select(-lines) %>% 
  drop_na()

write.csv(df.bates, "../../data/bates.csv")



```

# Brown

```{r}



folder_paths = c("../../data/Brown/Adam", "../../data/Brown/Eve", "../../data/Brown/Sarah")

folder_names = c("Adam", "Eve", "Sarah")

df_list = map2(folder_paths, folder_names, ~ {
  folder_path = .x
  folder_name = .y
  
  list_of_files = list.files(path = folder_path, pattern = ".cha", full.names = TRUE)
  
  df_list_files = map(list_of_files, ~ {
    data = read_lines(.x)
    data = enframe(data, name = NULL) %>% 
      mutate(file = basename(.x),
             folder_index = folder_name,
             age = as.numeric(str_extract(basename(.x), "\\d{2}")))
    data
  })
  
  df_folder = bind_rows(df_list_files)
  df_folder
})

df.brown = bind_rows(df_list)


```

```{r}

  df.brown = df.brown %>% 
  clean_names() %>% 
   mutate(mother = str_extract(value, "(?<=MOT:)(.*)"),
          child = str_extract(value, "(?<=CHI:)(.*)")) %>% 
  pivot_longer(cols = mother:child,
               names_to = "person_speaking",
               values_to = "text") %>% 
   mutate(participant = match(file_index, unique(file_index)),
          child_gender = if_else(file_index %in% c("Eve", "Sarah"), "female", "male"),
          format = rep("lab")) %>% 
  select(-file, -value) %>% 
  drop_na() 

write.csv(df.brown, "../../data/brown.csv")


```



#DATA
# Molly Lewis Children (Gender) Books Corpus

```{r}

df.books <- read_csv("../../data/wcbc_by_book.txt", col_names = TRUE)
```

# Book Corupos with GPT3 Annotations

## Read in data

```{r}

df.books.gpt3 = read_csv("../../data/annotation_sample_split.csv")

```

## Wrangle 

```{r}
df.books.gpt3 = df.books.gpt3 %>% 
  separate(gpt_3_categorization_split,
           into = c("item", "kind", "description", "property"),
           sep = ",")
  
```

## Export CSV to start to work with

```{r}

df.books.gpt3_clean = df.books.gpt3 %>% 
  separate(gpt_3_categorization_split,
           into = c("item", "kind", "description", "property"),
           sep = ",") %>% 
    mutate(kind = trimws(kind, which = "left"),
         property = trimws(property, which = "left"),
         item = trimws(item, which = "left"),
         description = trimws(description, which = "left")) %>% 
  filter(kind %in% c("artifact", "animal", "non-living natural kind"), property %in% c("appearance", "behavioral", "purpose", "location"))

write.csv(df.books.gpt3_clean, "../../data/books_bert.csv")


  
```


# PLOTS

## Kind by property

```{r}

df.plot = df.books.gpt3 %>% 
  select(age, item:property) %>% 
  drop_na() %>% 
  group_by(age, kind) %>%
  count(property, sort=TRUE) %>%
  ungroup() %>%
  mutate(kind = trimws(kind, which = "left"),
         property = trimws(property, which = "left")) %>% 
  filter(kind %in% c("artifact", "animal", "non-living natural kind"), property %in% c("appearance", "behavioral", "purpose", "location"))
 

ggplot(data = df.plot,
       aes(x = kind, y = n, color = property, fill = property)) +
  geom_col(position = "dodge") +
   scale_fill_brewer(palette = "Set1") + 
  scale_color_brewer(palette = "Set1") +
  theme_classic() +
  ylab("count") +
  theme(axis.title.x = element_blank())
  

 ggsave(height = 4, width = 6, "../../figures/kind_property.pdf")
```

## Property by kind
```{r}

ggplot(data = df.plot,
       aes(x = property, y = n, color = kind, fill = kind)) +
  geom_col(position = "dodge") +
   scale_fill_brewer(palette = "Set1") + 
  scale_color_brewer(palette = "Set1") +
  theme_classic() +
  ylab("count") +
  theme(axis.title.x = element_blank())
  

 ggsave(height = 4, width = 6, "../../figures/property_kind.pdf")
```
## Kind by property by age

```{r}

ggplot(data = df.plot,
       aes(x = kind, y = n, color = property, fill = property)) +
  geom_col(position = "dodge") +
   scale_fill_brewer(palette = "Set1") + 
  scale_color_brewer(palette = "Set1") +
  theme_classic() +
  ylab("count") +
  theme(axis.title.x = element_blank()) +
  facet_wrap(~age)
  

 ggsave(height = 8, width = 15, "../../figures/kind_property_age.pdf")
```
## Property by kind by age
```{r}

ggplot(data = df.plot,
       aes(x = property, y = n, color = kind, fill = kind)) +
  geom_col(position = "dodge") +
   scale_fill_brewer(palette = "Set1") + 
  scale_color_brewer(palette = "Set1") +
  theme_classic() +
  ylab("count") +
  theme(axis.title.x = element_blank()) +
  facet_wrap(~age)
  

 ggsave(height = 8, width = 15, "../../figures/property_kind_age.pdf")
```

## Individual animals and properties

```{r}

df.plot = df.books.gpt3 %>% 
  select(age, item:property) %>% 
  drop_na() %>% 
  group_by(age, item, kind) %>%
  count(property, sort=TRUE) %>%
  ungroup() %>% 
  mutate(kind = trimws(kind, which = "left"),
         property = trimws(property, which = "left"),
         item = trimws(item, which = "left"))




ggplot(data = df.plot,
       aes(x = kind, y = n, color = property, fill = property)) +
  geom_col(position = "dodge") +
  theme_classic() +
  ylab("count") +
  theme(axis.title.x = element_blank())

 ggsave(height = 10, width = 50, limitsize = FALSE, "../../figures/everything.pdf")

```